openapi: 3.0.1
info:
  version: 0.0.1
  title: Consent mediator api
# during dev, should point to your local machine
servers:
  - url: https://localhost:10010/v2
  - url: http://localhost:10010/v2
paths:
  /consent:
    get:
      operationId: getConsent
      tags:
        - getConsent
      summary: Request for consent
      description: Returns a consent by customer and processId i.e. decisionId
      parameters:
      - name: customerId
        description: Customer id, temporarily ssn
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Ssn'
      - name: processId
        description: The initiating process id such as the benefit application case id
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Identifier'
      - name: includeMeta
        description: Indicates whether to include additional metadata in response
        in: query
        schema:
          type: boolean
          default: true
      responses:
        200:
          description: Consent data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentData'
        default:
          description: Error getting consent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      operationId: addConsent
      tags:
        - addConsent
      summary: Adds a consent for a customer (internally adds a customer account if needed)
      description: Adds a new consent to a customer. Can be a nested consent
      requestBody:
        description: Consent data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentCreationRequest'
      responses:
        200:
          description: Consent data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentData'
        default:
          description: Error adding consent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    patch:
      operationId: updateConsent
      tags:
        - updateConsent
      summary: Modify single consent in consent data
      requestBody:
        description: Consent data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentUpdateRequest'
      responses:
        200:
          description: Consent data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentUpdateResponse'
        default:
          description: Error modifying consent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /revoke:
    post:
      tags:
      - revoke
      operationId: revoke
      summary: Revokes a consent
      description: Revokes the consent as a group or a single consent within the group of consents if targetConsentId is given in request.
      requestBody:
        description: Consent data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RevokationRequest'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RevokationResponse'
  /consents:
    get:
      operationId: getConsents
      tags:
        - getConsents
      summary: Request for consent
      description: Returns a consent by customer
      parameters:
      - name: customerId
        description: The customer whose consents are returned, temporarily ssn
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Ssn'
      - name: context
        description: Context code or name, i.e. rehabilitation
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Ssn'
      responses:
        200:
          description: All consents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConsentData'
components:
  schemas:
    ConsentCreationRequest:
      type: object
      required:
      - creator
      - consentData
      - origin
      - context
      properties:
        consent:
          $ref: '#/components/schemas/ConsentData'
        origin:
          $ref: '#/components/schemas/ConsentOrigin'
        context: #Code value of the consent context, such as benefit type
          type: string
        creator:
          $ref: '#/components/schemas/ConsentHandler'
    ConsentUpdateRequest:
      type: object
      anyOf:
      - required: [reason]
      - required: [dateRange]
      required:
      - consentId
      - reason
      properties:
        consentId:
          $ref: '#/components/schemas/Identifier'
        reason:
          type: string
        dateRange:
          $ref: '#/components/schemas/DateRange'
        targets:
          type: array
          items:
            $ref: '#/components/schemas/ConsentTarget'
        modifier:
          $ref: '#/components/schemas/ConsentHandler'
    ConsentUpdateResponse:
      type: object
      properties:
        modifiedConsent:
          $ref: '#/components/schemas/Consent'
        modificationTime:
          $ref: '#/components/schemas/DateTime'
    RevokationRequest:
      type: object
      anyOf:
      - required: [processId]
      - required: [targetConsentIds]
      required:
      - revoker
      properties:
        customerId:
          $ref: '#/components/schemas/Ssn'
        processId:
          $ref: '#/components/schemas/Identifier'
        targetConsentIds:
          type: array
          items:
            $ref: '#/components/schemas/Identifier'
        reason:
          type: string
        revoker:
          $ref: '#/components/schemas/ConsentHandler'
    RevokationResponse:
      type: object
      properties:
        status:
          type: integer
        consentId:
          type: string
          format: uuid
        result:
          type: boolean
    ConsentData:
      type: object
      required:
      - processId
      - consents
      - personalId
      - metadata
      properties:
        processId:
          $ref: '#/components/schemas/Identifier'
        consents:
          type: array
          items:
            $ref: '#/components/schemas/Consent'
        metadata:
          $ref: '#/components/schemas/ConsentMeta'
        personalId:
          $ref: '#/components/schemas/Ssn'
    ConsentMeta:
      type: object
      required:
      - origin
      - creator
      - context
      properties:
        origin:
          type: string
          enum:
          - benefitApplication
          - webApp
          - mobileClient
          - phoneConversation
          - office
          - print
        context: #Code value of the consent context, such as benefit type
          type: string
        creator:
          $ref: '#/components/schemas/ConsentHandler'
        modifier:
          type: array
          items:
            $ref: '#/components/schemas/ConsentHandler'
        created:
          $ref: '#/components/schemas/DateTime'
    Consent:
      type: object
      required:
      - id
      - reason
      - text
      - dateRange
      - targets
      properties:
        id: 
          $ref: '#/components/schemas/Identifier'
        reason:
          type: string
        previousReasons:
          type: array
          items:
            type: string
        dateRange:
          $ref: '#/components/schemas/DateRange'
        previousReasonsDateRanges:
          type: array
          items:
            $ref: '#/components/schemas/DateRange'
        description:
          type: string
        text:
          type: string
        targets:
          type: array
          items:
            $ref: '#/components/schemas/ConsentTarget'
    ConsentTarget:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Identifier'
        name:
          type: string
        active:
          type: boolean
        targetType:
          type: string
          enum:
          - documentExchange
          - conversation
          - dataInquiry
          - automaticProcessing
    ErrorResponse:
      type: object
      #errorCode tai message pakollinen
      required:
      - status
      - errorCodes
      - message
      properties:
        status:
          type: integer
        errorCodes:
          type: array
          items:
            type: string
        message:
          type: string
        #can be replaced by error code
        decisionActive:
          type: boolean
    ConsentHandler:
      type: object
      anyOf:
      - required: [id] # forces both name and businessId for service prodiver users or neither for customer
      - required: [name, businessId]
      required: 
      - id
      - creatorType
      properties:
        id:
          description: either account id, personal ssn
          type: string
        businessId:
          $ref: '#/components/schemas/BusinessId'
        name:
          type: string
        creatorType:
          type: string
          enum:
          - customer
          - benefitHandler
          - publicOfficial
          - privateOfficial
          - healthcare
    ConsentOrigin:
      type: string
      enum:
      - benefitApplication
      - webApp
      - mobileClient
      - phoneConversation
      - office
      - print
    Ssn:
      type: string
      pattern: '^\d{6}[A-]\d{3}[a-zA-Z0-9]$'
    BusinessId:
      type: string
      pattern: '/^[\d]{7}-[\d]$'
    Identifier:
      type: string
      format: uuid
    DateRange:
      type: object
      required:
      - startDate
      - endDate
      properties:
        startDate:
          $ref: '#/components/schemas/Date'
        endDate:
          $ref: '#/components/schemas/Date'
    Date: 
      type: string
      format: date
    DateTime: 
      type: string
      format: datetime
